### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by atticoos** [SandersForPresident/bootstrap#1]
Would be nice to get this registered in `bower` under the name `berniestrap` or something

**Comment by MattPetitt** [comment]
berniestrap is now on bower!

**Comment by cockroachbill** [comment]
Can someone give me tips on how to integrate this into a project through Bower?

**Comment by atticoos** [comment]
`bower install git@github.com:SandersForPresident/bootstrap.git` or, to avoid breaking changes that may become committed 

`bower install git@github.com:SandersForPresident/bootstrap.git#ce07b61` (`ce07b61` being the current `HEAD` sha1)

**Comment by atticoos** [comment]
Oh i forgot this is up on bower, just need to do `bower install berniestrap --save`
